// Research Points economy + company Research Projects. PURE.
import { BALANCE } from "./balance.ts";
import { disciplineOutput } from "./staff.ts";
import type { Staff } from "./types.ts";

export type ProjectId =
  | "assemblyLine"
  | "leanSupply"
  | "brandStudio"
  | "talentNetwork"
  | "globalDistribution"
  | "qaLab";

export interface ResearchProject {
  id: ProjectId;
  name: string;
  blurb: string;
  rpCost: number;
  era: number; // minimum era to research
}

export const RESEARCH_PROJECTS: ResearchProject[] = [
  { id: "assemblyLine", name: "Assembly Line", blurb: "Manufacture products faster.", rpCost: 28, era: 1 },
  { id: "leanSupply", name: "Lean Supply Chain", blurb: "Cut per-unit build cost by 15%.", rpCost: 44, era: 1 },
  { id: "qaLab", name: "QA Lab", blurb: "Bigger reputation gains, softer flops.", rpCost: 38, era: 1 },
  { id: "talentNetwork", name: "Talent Network", blurb: "Hiring fees 40% cheaper.", rpCost: 52, era: 2 },
  { id: "brandStudio", name: "Brand Studio", blurb: "Every launch gets more hype.", rpCost: 66, era: 2 },
  { id: "globalDistribution", name: "Global Distribution", blurb: "Reach 25% more customers.", rpCost: 96, era: 3 },
];

export function projectById(id: ProjectId): ResearchProject {
  return RESEARCH_PROJECTS.find((p) => p.id === id)!;
}

/** Weekly RP generated by staff assigned to R&D (+ founder trickle), scaled by era. */
export function weeklyRp(staff: readonly Staff[], era: number): number {
  let rp = BALANCE.research.rpFounderBase;
  for (const s of staff) {
    if (s.assignment !== "rnd") continue;
    // R&D draws on the person's Engineering discipline (0..100). Engineers naturally score high
    // here; a non-engineer with decent Engineering still contributes.
    const per =
      s.role === "engineer"
        ? BALANCE.research.rpPerEngineerSkill
        : BALANCE.research.rpPerAssignedResearcher;
    rp += disciplineOutput(s, "engineering") * per;
  }
  const len = BALANCE.research.eraMultiplier.length;
  const mult = BALANCE.research.eraMultiplier[Math.max(1, Math.min(era, len)) - 1];
  return rp * mult;
}

/** Convert an old cash R&D cost into an RP cost for a component tier. */
export function techRpCost(cashRdCost: number): number {
  return Math.max(BALANCE.research.minTechRp, Math.round(cashRdCost * BALANCE.research.rdCashToRp));
}

export function hasProject(completed: readonly ProjectId[], id: ProjectId): boolean {
  return completed.includes(id);
}
