import Foundation

/// Which implementation backs the purchase half of `SiliconStoreKit`.
///
/// This is the ONE switch for the whole RevenueCat migration. Flipping it back to `.storeKit2` is a
/// one-line, zero-risk revert: the StoreKit 2 code in `SiliconStoreKit.swift` is left completely
/// intact, not deleted, precisely so that reverting costs nothing on a bad release day.
enum SiliconStoreBackend {
    /// Apple's StoreKit 2, on-device, no third party. The original implementation.
    case storeKit2
    /// RevenueCat's iOS SDK, wrapped inside this same Capacitor plugin so the JS seam is unchanged.
    case revenueCat
}

/// RevenueCat wiring — key, entitlement identifier, and the backend decision.
///
/// ── WHY THE SDK IS EMBEDDED THIS WAY ────────────────────────────────────────────────────────────
/// This app's iOS target is **Swift Package Manager only** (`ios/App/CapApp-SPM/Package.swift`, no
/// `Podfile`). The official `@revenuecat/purchases-capacitor` plugin cannot be used here: the line
/// that supports Capacitor 6 (9.x) ships a CocoaPods podspec and **no** `Package.swift`, and the
/// first version that does ship one (12.0.0) requires Capacitor 8. RevenueCat's *native* iOS SDK,
/// however, is SPM-native, targets iOS 13+, and pulls no runtime third-party dependencies — so it
/// drops straight into the existing plugin under the existing 15.0 deployment target.
///
/// ⚠️ Add the package to the **App target in `App.xcodeproj`**, NOT to `CapApp-SPM/Package.swift`.
/// That file is regenerated by `npx cap sync ios` from installed npm plugins and any hand-edit is
/// erased on the next sync. See `appstore/REVENUECAT_SETUP.md` §3 for the exact Xcode steps.
///
/// ── FAIL-SAFE BY CONSTRUCTION ───────────────────────────────────────────────────────────────────
/// Two independent conditions must BOTH hold before a single purchase call reaches RevenueCat:
///
///   1. the `RevenueCat` module is importable (the SPM package is actually linked), and
///   2. a non-empty public API key is configured.
///
/// If either is false the plugin silently keeps using StoreKit 2 — the code that ships today. That
/// means this file can land on `main` before the package is added, before the key exists, and before
/// the dashboard is configured, and the app's behaviour is byte-identical to what it does now.
enum RevenueCatConfig {

    /// The RevenueCat entitlement every Pro SKU is attached to. Must match the identifier created in
    /// the RevenueCat dashboard exactly (see `appstore/REVENUECAT_SETUP.md` §5).
    static let entitlementIdentifier = "pro"

    /// Emergency brake. Set to `true` to force StoreKit 2 even with the SDK linked and a key set —
    /// a one-character patch release if RevenueCat has an outage or a bad SDK version ships.
    static let forceStoreKit2 = false

    /// The **public** SDK key (`appl_…`). Public keys are designed to be embedded in the client and
    /// are safe in source control; the **secret** key must NEVER enter this repo.
    ///
    /// Set `RevenueCatPublicAPIKey` in `Info.plist` (or via an xcconfig) to override it per build —
    /// useful if a second RevenueCat project is ever added. The constant below is the default.
    ///
    /// Project: `Silicon: Tech Tycoon` (`78cb2b78`) · App: `Silicon: Tech Tycoon (App Store)`
    /// (`app706e1b1a3d`), bundle id `com.wrexist.silicon`.
    private static let builtInPublicAPIKey = "appl_jsQcYdrdXfaErHQdTjnUbKvqOVT"

    /// Resolved key: Info.plist wins, then the built-in constant. Empty means "not configured", and
    /// an unconfigured app deliberately stays on StoreKit 2 rather than half-initialising a store.
    static let publicAPIKey: String = {
        let fromPlist = Bundle.main.object(forInfoDictionaryKey: "RevenueCatPublicAPIKey") as? String
        let resolved = (fromPlist ?? builtInPublicAPIKey).trimmingCharacters(in: .whitespacesAndNewlines)
        return resolved
    }()

    /// True only when the SDK is linked AND a key is configured AND the brake is off.
    static var isAvailable: Bool {
        if forceStoreKit2 { return false }
        if publicAPIKey.isEmpty { return false }
        #if canImport(RevenueCat)
        return true
        #else
        return false
        #endif
    }

    /// The backend every plugin method routes through.
    static var backend: SiliconStoreBackend {
        return isAvailable ? .revenueCat : .storeKit2
    }
}
